### ISSUE TITLE
win11 局域网 点新建游戏闪退

### ISSUE THREAD

**Issue by iGwkang** [moshowgame/ra2yuri#9]
如题。

**Comment by iGwkang** [comment]
应该是网络库崩了，我网卡设置了跃点数，zerotier网卡的跃点数设置成1，有线网卡的跃点数设置成了100。这样游戏必崩。
我后面把有线网卡跃点数改成了2，才正常。用WiFi也正常，但是wifi网卡我没有修改跃点数，用的自动的

**Comment by moshowgame** [comment]
亲，跃点这个是啥，超出理解范围了哈哈，但是anyway，可以了就好



在 2024-03-17 17:40:05，"Gwkang" ***@***.***> 写道：

应该是网络库崩了，我网卡设置了跃点数，zerotier网卡的跃点数设置成1，有线网卡的跃点数设置成了100。这样游戏必崩。
我后面把有线网卡跃点数改成了2，才正常。用WiFi也正常，但是wifi网卡我没有修改跃点数，用的自动的

**Comment by iGwkang** [comment]
![image](https://github.com/moshowgame/ra2yuri/assets/35400668/1de3c452-3e34-4325-944b-f18c6f440402)
多网卡的情况下，跃点数可以理解为路由的优先级，范围是 0~255，跃点数越低，路由优先级越高。
假如电脑上有 eth0和eth1两个网卡，eth0的ip是 10.0.0.11，eth1的ip是 192.168.0.111，这两张网卡都能访问互联网。但是系统默认情况下只会选择其中一个(假如是eth0)，这样的话，有一些游戏就无法和 eth1局域网中的电脑连接（比如 魔兽争霸3），这个时候就要修改跃点数，让eth1的优先级比eth0高才行
